version: 1
jobs:
  build:
    dependencies: 
      cache_directories:
        - "/nix"
    machine: true
    steps:
      - checkout
      - run:
          name: Install Nix
          # Note: we need to install stack since we can't run the tests directly from the nix-build 
          # command because of some cabal-helper dark magic.
          command: 'sudo mkdir -p /nix && sudo chown circleci /nix && curl https://nixos.org/nix/install | sh && echo "source ~/.nix-profile/etc/profile.d/nix.sh" >> ~/.circlerci && source ~/.circleci && nix-env -i stack'
      - run:
          name: Run Ex-Hack test suite
          command: 'source ~/.circlerci && mkdir -p test/integration/workdir test/integration/output && nix-shell --run "cabal test"'
